version: '3.7'

services:
  backend:
    build:
      context: ./spring-kotlin
      dockerfile: Dockerfile
    container_name: spring-kotlin
    ports:
      - "8080:8080"
    restart: always
    environment:
      SERVER_PORT: 8080
      MAIL_HOST: host
      MAIL_PROTOCOL: protocol
      MAIL_USERNAME: username
      MAIL_PASSWORD: password
    networks:
      - backend
  frontend:
    build:
      context: ./react-typescript
      dockerfile: Dockerfile
    container_name: react-typescript
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - backend
networks:
  backend: